### ISSUE TITLE
Control over table border

### ISSUE THREAD

**Issue by rgknight** [gforge/htmlTable#12] opened 2016-09-06 00:34 UTC
It would be most excellent to gain control over the overall table borders. This would involve changing the api, though, replacing `ctable` with something like `tableborders = c("none", "single", "double")`. Lower priority, but it could perhaps also allow users to pass a list (?) where the first element is the css for the top boarder and the second element is the cc for the bottom border. 

Is a change to the ctable syntax something you would be open to?

**Comment by gforge** [comment] 2016-09-07 07:37
Sounds like an excellent suggestion. I have a few other projects that require my attention right now but this will be a good extension. I don't see why it has to be a list though as the variable will only contain a vector, I suggest:
- "none", "single", "double"
- combination of above if the vector has `length(...)==2`
- directly css-style borders, e.g. `border: 1px solid red` - this will need to be converted to border-top for the top and border-bottom for the bottom border.

Feel free to send a pull request if you feel you have the time

**Comment by raredd** [comment] 2016-09-16 22:27
@rgknight Couldn't this be implemented with something as simple as

``` r
## ctable can be logical or any combination of none, single, double

## first if is unchanged to prevent breaking code
if (isTRUE(ctable)) { ## was "if (ctable)"
    top_row_style = "border-top: 2px solid grey;"
    bottom_row_style = "border-bottom: 2px solid grey;"
  ## only change--add extra conditional
  } else if (any(ctable %in% c('single', 'double'))) {
    ctable <- rep_len(ctable, 2L)
    ctable[ctable %in% 'single'] <- 'solid'
    top_row_style = sprintf("border-top: 4px %s grey;", ctable[1])
    bottom_row_style = sprintf("border-bottom: 2px %s grey;", ctable[2])
## no changes
  } else ...
```

This obviously won't affect the color or width. If that was the intention, it might be easier just to add a `css.top.row = "border-top: 2px solid grey;"` and a `css.bottom.row = "border-bottom: 2px solid grey;"` argument

**Comment by gforge** [comment] 2016-09-18 09:36
Thanks, I've added it to the dev-version so you can check it out. The double has though also a larger pixel height as it otherwise appears as a single line. I've changed so it should work.

I feel though that this solution is a little hacky and doesn't allow full customization, e.g. color of the lines etc.

**Comment by raredd** [comment] 2016-09-18 16:11
Works great, Max!

On a side note giving the user the option to control the style, size, color, etc for every table attribute might be overkill. If one so desires, this could always be changed after the table is generated in the css file or like below in the table string itself.

We can use either the class or an id so these changes won't be applied to every table

```
# devtools::install_github('gforge/htmlTable', ref = 'develop')

x <- htmlTable::htmlTable(head(cars), caption = 'a gmisc table')
y <- gsub('gmisc_table', '', htmlTable::htmlTable(head(cars), caption = 'not a gmisc table'))
two_tables <- paste(x, '<br />', y)
attributes(two_tables) <- attributes(x)
two_tables


## class selector
css <- '<style>.gmisc_table th, .gmisc_table td{border-color: red !important;}</style>'
gsub('^', css, two_tables)
```

![1](http://i.imgur.com/zTCRSj3m.png)

``` r
## add id to gmisc_table
x <- gsub('(?<=.gmisc_table.)', ' id = \'gmisc_table\'', x, perl = TRUE)
two_tables <- paste(x, '<br />', y)
attributes(two_tables) <- attributes(x)


css <- '
<style>
#gmisc_table th {
  border-top-color: red !important;
  border-bottom-color: green !important;
}

/* use id to select last tr _only_ in the table body              */
/* the class selector approach above would select last tr in both */
#gmisc_table>tbody> tr:last-child {
  border-bottom: 5px dashed red !important;
}
</style>'
gsub('^', css, two_tables)
```

![2](http://i.imgur.com/dFM4w2sm.png)

I'm just fumbling my way through this css stuff, so if I've made this more difficult than needed, please fix.

**Comment by gforge** [comment] 2016-09-18 17:06
Thanks. You're probably right about the letting the user rely on their own css-skills for this. That is the intention of the gmis_table css class, the problem is that css isn't captured when copying to word-processors if it's in the style-sheet. This seems though as a negligible concern for a feature such as this. 

You're css code is fine although `#` is set using the `label` option while the `gmis_table` should be used for class referring to all tables. 

I'll close this issue for now but if I get new request I'll consider switching to a more general approach.

**Closed as completed by gforge** 2016-09-18 17:06 UTC
Labels: enhancement
