### ISSUE TITLE
Question about css.cell

### ISSUE THREAD

**Issue by jeffmun** [gforge/htmlTable#1] opened 2015-02-17 22:00 UTC
Thanks for this package, it is great.  Some questions about css.cell.  In order to set it directly I need to insert a semi-colon at the start of my formatting string.  Here is an example, I want the column named "M" in my data frame to be bold, so I create a second data frame containing the CSS formatting (in this case "font-weight: bold") in the relevant cells.  In the output I get:  <td style='M: font-weight: bold; text-align: center;'>123</td> 
The extra "M: " makes the "font-weight: bold;" not render.  So instead, I use "; font-weight: bold" and it renders correctly.  In all cases the column name with a colon appears as the first entry in the style string.  Am I using this wrong?  Second, Is there a way to to directly set the CSS class for a cell rather than use the style?  I don't need this necessarily, but was curious.  Thanks again for this great tool!

**Comment by gforge** [comment] 2015-02-18 09:22
Unfortunately I can't reproduce your bug:

``` r
mx <- matrix(1:6, ncol=3)
colnames(mx) <- c("A", "B", "C")
rownames(mx) <- letters[1:2]

# Formatting the middle to be bold
htmlTable(mx, 
          css.cell = c("", "font-weight: bold", ""))

# Column formatting example
htmlTable(mx, 
          css.cell = c("", "font-weight: bold; font-size:2em; color: red", ""))

# Cell specific formatting
htmlTable(mx, 
          css.cell = rbind(c("", "font-weight: bold; font-size:2em; color: red", ""),
                           c("", "color: red", "")))
```

**Comment by jeffmun** [comment] 2015-02-18 19:38
Thanks for the quick response.  I found the issue.  When using a data frame or matrix with named columns, this issue comes up.  It is solved when removing the names and casting as a matrix.  
I am dynamically creating my css.cell formatting in a data frame in code.  I will remove the names as cast as a matrix and I suspect that will work for me.  I don't know if this is worth addressing in your code or just to clarify in the documentation.  I really appreciate this package.  Take care.

``` R

mx <- matrix(1:6, ncol=3)
colnames(mx) <- c("A", "B", "C")
rownames(mx) <- letters[1:2]

# Define the css.cell input within a data frame
df_css <- data.frame(rbind(c("", "font-weight: bold; font-size:2em; color: red", ""),
                           c("", "color: red", "")))
df_css_nonames <- df_css
names(df_css_nonames) <- NULL     ## Remove the col names

# cast the css.cell info as a matrix
mx_css <- as.matrix(df_css) 
mx_css_nonames <- as.matrix(df_css_nonames) 

# Cell specific formatting: 
# df of css --> col names introduced into "style" tag
htmlTable(mx, 
          css.cell = df_css)

# df of css with no names --> ERROR
htmlTable(mx, 
          css.cell = df_css_nonames)

# matrix of css --> again, col names introduced into "style" tag
htmlTable(mx, 
          css.cell = mx_css)

# matrix of css with no names --> SUCCESS
htmlTable(mx, 
          css.cell = mx_css_nonames)
```

**Comment by gforge** [comment] 2015-02-18 21:00
Great. The bug should now be fixed in the develop version.

**Closed as completed by gforge** 2015-02-18 21:00 UTC
