### ISSUE TITLE
tidyHtmlTable does not accept multiple rgroup

### ISSUE THREAD

**Issue by HoneyBuddha** [gforge/htmlTable#70] opened 2019-11-04 09:39 UTC
**Describe the bug**
Hi, Thank you for this wonderful package. 

I have noticed that - the tidyHtmlTable wrapper does not allow rnames or rgroup to accept anything other than a character string. Thus, nested row groups are not able to be passed to the function. 

**To Reproduce**
```
tidy.DF_FULL  %>%
  tidyHtmlTable(x = .,
                header = "ColumnLevel02",
                cgroup1 = "ColumnLevel01",
                value = "formattedValue",
                rnames = "RowLevel03",
                rgroup = c("RowLevel01", "RowLevel02"))

```
creates the following error:
> Error in argument_checker(x, value = value, header = header, rnames = rnames,  : 
  The following parameters must be of type character:  rgroup

**Expected behavior**
Row Level 2 would be nested within Row Level 1 - just like Row Level 3 is nested within Row Level 2
i.e. Rows would be nested Level 1 > Level 2 > Level 3

**Versions (please complete the following information):**
 - OS: Windows 10
 - R IDE: RStudio
 - Package version: 1.13.1

**Additional context**
The Tidy Html Table wrapper is fantastic and works perfectly in all over situations. It is simply not responding to multiple nested groups. Is it possible to get an interim data structure out that could be manipulated before rendering in html?

**Comment by graggsd** [comment] 2019-11-04 15:14
Hi, I contributed this function a while back while I was working on my dissertation project. At the time, my boss was asking me to build some crazy complicated tables that took forever to format by hand. That said, the purpose of this function is just a wrapper for HtmlTable that is meant to facilitate tidy syntax and help automate ordering and building the table. That said, at the time HtmlTable (probably still does) handled nested row groups using rnames, rgroup, and tspanner. There were no additional ways to build extra levels of row nesting. That said, tidyHtmlTable also only allows nesting of rows using these parameters. While what you have suggested sounds like a nifty function (I asked for this feature in HtmlTable at one time), ultimately I don't have the bandwidth to build it out AND there is the practical consideration that having more than 3 groups of row nesting within a table may be a little impractical and hard for the intended audience to decipher in the first place.

**Comment by gforge** [comment] 2019-11-04 17:57
Yeah, too much nesting can be tricky just from a visual perspective and probably the design is not what was intended. Although I'm not sure I fully understand the problem, could you provide a full example with a raw htmlTable version so that I can see what you're trying to generate?

**Comment by graggsd** [comment] 2019-11-04 20:02
I suspect the expected result of this input:

```
tidy.DF_FULL  %>%
  tidyHtmlTable(x = .,
                header = "ColumnLevel02",
                cgroup1 = "ColumnLevel01",
                value = "formattedValue",
                rnames = "RowLevel03",
                rgroup = c("RowLevel01", "RowLevel02"))
```
Could alternatively be achieved by doing this instead:

```
tidy.DF_FULL  %>%
  tidyHtmlTable(x = .,
                header = "ColumnLevel02",
                cgroup1 = "ColumnLevel01",
                value = "formattedValue",
                rnames = "RowLevel03",
                rgroup = "RowLevel02",
                tspanner = "RowLevel01")
```
As with the original `htmlTable` function for which `tidyHtmlTable` acts as a wrapper, there is currently no ability to add nested rgroups.

**Comment by HoneyBuddha** [comment] 2019-11-05 01:34
Hi,

Thank you for your insight and for this very helpful wrapper function.

Unfortunately,  I'm currently traveling today, so I don't have access to
any coding devices, but I'll try to produce a reproducible dataset to
share with you tomorrow once I land.

I can also share a sample table to show how the nesting is being used and
(-at least in the current case) is actually useful for guiding the reader
(rather than bombarding them with a data overload).

I'm curious to see if the tspanner solution may actually be able to
accomplish the same. I'll give it a try and let you know as well.

Thanks again. Looking forward to getting back to you once I am back.

Best wishes,
Anirudh

-sent from my phone

**Comment by gforge** [comment] 2020-09-15 12:38
Closing the issue as it seems resolved

**Closed as completed** 2020-09-15 12:38 UTC
