### ISSUE TITLE
Error with css.cell if dataset has one row

### ISSUE THREAD

**Issue by taunometsalu** [gforge/htmlTable#54] opened 2018-02-06 12:27 UTC
If dataset has one row only and I try to use css.cell with matrix where nrow is one greater than the number of rows (to apply the formatting also to header), the function `htmlTable` gives an error.

```
> d = iris[1, ]
> cssMatrix = matrix("padding-left: .5em;", nrow = nrow(d) + 1, ncol = ncol(d))
> htmlTable(d, css.cell = cssMatrix)
Error in css.cell[row_nr, ] : incorrect number of dimensions
```

The same code works if there are more rows. Probably, the error is caused by a missing `drop = FALSE` when filtering the rows.

**Comment by lemna** [comment] 2018-02-07 14:52
Thanks for the report. Something goes wrong indeed.
For reference, the following is the documented/expected behaviour:

> If css.cell is a vector, it's assumed that the styles should be repeated throughout the columns (that is, each element in css.cell specify the style for the whole row of 'x').
> 
> In the case of css.cell being a matrix of the same size of the x argument, each element of x gets the style from the corresponding element in css.cell. Additionally, the number of rows of css.cell can be nrow(x) + 1 so the first row of of css.cell specifies the style for the header of x; also the number of columns of css.cell can be ncol(x) + 1 to include the specification of style for row names of x.

Some further test cases to be added to the tests:
```
library(htmlTable)
data(iris)

# error: 1 row data, 2 row css.cell
d <- iris[1, ]
cssMatrix <- matrix("padding-left: .5em;", nrow = nrow(d) + 1, ncol = ncol(d))
htmlTable(d, css.cell = cssMatrix)

# no error: 2 row data, 3 row css.cell
d <- iris[1:2, ]
cssMatrix <- matrix("padding-left: .5em;", nrow = nrow(d) + 1, ncol = ncol(d))
htmlTable(d, css.cell = cssMatrix)

# no error: 2 row data, 2 row css.cell
d <- iris[1:2, ]
cssMatrix <- matrix("padding-left: .5em;", nrow = nrow(d), ncol = ncol(d))
htmlTable(d, css.cell = cssMatrix)

# error: 1 row data, 1 row/6 column css.cell
d <- iris[1, ]
cssMatrix <- matrix("padding-left: .5em;", nrow = nrow(d), ncol = ncol(d) + 1)
htmlTable(d, css.cell = cssMatrix)

# no error: 2 row data, 2 row/6 column css.cell; css is not applied to second row
d <- iris[1:2, ]
cssMatrix <- matrix("padding-left: .5em;", nrow = nrow(d), ncol = ncol(d) + 1)
htmlTable(d, css.cell = cssMatrix)

# no error: 2 row data, 3 row/6 column css.cell
d <- iris[1:2, ]
cssMatrix <- matrix("padding-left: .5em;", nrow = nrow(d)+1, ncol = ncol(d) + 1)
htmlTable(d, css.cell = cssMatrix)
```

**Comment by gforge** [comment] 2018-02-11 10:55
Awesome, I've just pushed a fix to the develop branch. Damn the `[,,drop=TRUE]` default in R. This must be one of the highest ranking design flaws in R - I don't know how many edge cases I've been fixing throughout the years due to this *feature*. If I don't hear back in a few days I'll push the fix to CRAN.

**Closed as completed** 2018-03-16 19:16 UTC

**Comment by juliendiot42** [comment] 2018-05-25 12:41
Hi when do you think this fix can be push on the CRAN ?

**Comment by gforge** [comment] 2018-05-25 23:07
I'll see if I can get around to it. They have made the process incredibly tedious why I try to avoid pushing minor fixes

**Comment by juliendiot42** [comment] 2018-05-28 11:52
Ok great thank you !  :)

**Comment by juliendiot42** [comment] 2018-05-28 15:25
I've just seen that your package has been updated on CRAN (v1.12) (thks to [CRANalert](https://cranalerts.com) )
It works well, Thank you !
